### ISSUE TITLE
automlst-wrapper issue

### ISSUE THREAD

**Issue by JackSun1997** [NBChub/bgcflow#278] opened 2023-08-28 08:23 UTC
Hello, I encountered an error while running bgcflow flow with parameters: 'roary', 'eggnog-roary' and 'mash'. I got the following error:
<img width="1197" alt="error_info" src="https://github.com/NBChub/bgcflow/assets/70607895/813e3386-d2c6-4a74-9656-399b62e488aa">
<img width="1021" alt="log_file" src="https://github.com/NBChub/bgcflow/assets/70607895/fca6cf44-e88c-4a94-aa49-1dda478feadb">
Could you please help me solve this issue? Thank you in advance!

**Comment by matinnuhamunada** [comment] 2023-08-28 09:43
Seems like the issue is with the accession GCF_9001679851? Is this an NCBI Assembly accession? I can't find it in NCBI

**Comment by matinnuhamunada** [comment] 2023-08-28 15:58
This is an interesting bug. Hmmer spew EOF error when the concatenated faa file generated by automlst contains empty sequence at the end of the file. Perhaps we should not include empty sequences in the first place

**Comment by matinnuhamunada** [comment] 2023-08-30 04:42
Fixed in https://github.com/NBChub/bgcflow/commit/67fd4639dd451f7170407c180f126eebf1f7435f

**Closed** 2023-08-30 04:42 UTC
